"""added new fields

Revision ID: 3007b5fc93ac
Revises: 46ec530e26a4
Create Date: 2026-04-16 23:44:08.041689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3007b5fc93ac'
down_revision: Union[str, Sequence[str], None] = '46ec530e26a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('address', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('issues', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('issues', sa.Column('is_rejected', sa.Boolean(), nullable=False))
    op.add_column('issues', sa.Column('upvotes', sa.Integer(), nullable=False))
    op.add_column('issues', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('escalated_at', sa.DateTime(), nullable=True))
    op.alter_column('issues', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('issues', 'created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('issues', 'assigned_to',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('issues', 'assigned_to',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('issues', 'created_by',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('issues', 'id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('issues', 'escalated_at')
    op.drop_column('issues', 'resolved_at')
    op.drop_column('issues', 'upvotes')
    op.drop_column('issues', 'is_rejected')
    op.drop_column('issues', 'is_verified')
    op.drop_column('issues', 'priority')
    op.drop_column('issues', 'address')
    # ### end Alembic commands ###
